feat: added search-line
Online-discount-card-service/odcs-frontend pull request #257
Opened 2023-11-27 20:11 UTC by Taswikaa

Сейчас фильтрация взаимодействует с глобальным контекстом карточек, думаю нужно будет сделать ещё один контекст для отсортированных карт.

2023-11-27 20:45 UTC, kavabunga commented
> Сейчас фильтрация взаимодействует с глобальным контекстом карточек, думаю нужно будет сделать ещё один контекст для отсортированных карт.

Сделаешь в этом ПР дальше или думаешь отдельной задачей это?

2023-11-27 21:00 UTC, Taswikaa commented
> > Сейчас фильтрация взаимодействует с глобальным контекстом карточек, думаю нужно будет сделать ещё один контекст для отсортированных карт.
> 
> Сделаешь в этом ПР дальше или думаешь отдельной задачей это?

в этом, завтра сделаю. Просто на обсуждение вынес дальнейшие действия, если вариант с отдельным контекстом для отсортированных карт нормально - делаю так (потом этот контекст можно юзать для сортировки чипсами)

2023-11-27 21:03 UTC, kavabunga commented
Да, это супер!27 нояб. 2023 г., в 23:00, Alekseev Sergey ***@***.***> написал(а):﻿


Сейчас фильтрация взаимодействует с глобальным контекстом карточек, думаю нужно будет сделать ещё один контекст для отсортированных карт.

Сделаешь в этом ПР дальше или думаешь отдельной задачей это?

в этом, завтра сделаю. Просто на обсуждение вынес дальнейшие действия, если вариант с отдельным контекстом для отсортированных карт нормально - делаю так (потом этот контекст можно юзать для сортировки чипсами)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2023-11-28 18:52 UTC, Taswikaa commented
Добавил контекст отсортированных карт, теперь в user-cards именно они отрисовываются. Если карт с таким названием нет, то в отсортированных картах будут все карты.

2023-11-29 12:05 UTC, kavabunga requested changes
Супер! Вот несколько коментов:

- Было бы классно, если список опций появлялся после ввода хотя бы 1 символа
- В списке должны быть только магазы из тех что есть у пользователя, включая его кастомные. Думаю надо из cards его брать
- Сейчас если написать в поле текст и не выбрать значение из списка, оно не будет искать. Даже если текст совпадает с одним из вариантов списка. Думаю, надо чтобы совпадающий текст принимался
- В идеале, конечно, искать и по фрагменту названия
- Если ответов не нашлось, нужно показывать специальный экран
- Дизайн компонента можно подвести к макету
- Сейчас при изменении конекста cards (добавление, удаление, лайк) не обновляется контекст sortedCards

[Актуальные макеты](https://www.figma.com/file/3SieWKz3TaNqmqWhlz0dSt/Online-discount-card-service?type=design&node-id=2314-13698&mode=dev)

2023-11-29 19:38 UTC, Taswikaa commented
> * Сейчас при изменении конекста cards (добавление, удаление, лайк) не обновляется контекст sortedCards

Есть идеи как это можно пофиксить? сейчас при лайке или удалении приходят обновлённые карточки с сервера, то есть если пробрасывать их в отсортированные карточки, то сортировка слетает

2023-11-29 20:12 UTC, Taswikaa commented
> * Было бы классно, если список опций появлялся после ввода хотя бы 1 символа
Имеешь в виду список выпадает, только если поле ввода не пустое? Мне кажется, это наоборот хуже, чем когда оно сразу при взаимодействии выпадает
> * В списке должны быть только магазы из тех что есть у пользователя, включая его кастомные. Думаю надо из cards его брать
Готово
> * Сейчас если написать в поле текст и не выбрать значение из списка, оно не будет искать. Даже если текст совпадает с одним из вариантов списка. Думаю, надо чтобы совпадающий текст принимался
Готово
> * В идеале, конечно, искать и по фрагменту названия
Готово
> * Если ответов не нашлось, нужно показывать специальный экран
Он свёрстан уже или ещё нет? Если нет, в этом пре делаю?
> * Дизайн компонента можно подвести к макету
Вёрстку поправлю, но сначала функционал

2023-11-29 20:26 UTC, kavabunga commented
> > * Сейчас при изменении конекста cards (добавление, удаление, лайк) не обновляется контекст sortedCards
> 
> Есть идеи как это можно пофиксить? сейчас при лайке или удалении приходят обновлённые карточки с сервера, то есть если пробрасывать их в отсортированные карточки, то сортировка слетает

Надо может куда-то useEffect, который при обновлении cards обновлял бы и сортировку

2023-11-29 20:27 UTC, Taswikaa commented
> Надо может куда-то useEffect, который при обновлении cards обновлял бы и сортировку

Ок, я завтра доделаю оставшееся, и буду фиксить этот момент, он мне кажется самым тяжёлым

2023-11-29 20:29 UTC, kavabunga commented
> > Надо может куда-то useEffect, который при обновлении cards обновлял бы и сортировку
> 
> Ок, я завтра доделаю оставшееся, и буду фиксить этот момент, он мне кажется самым тяжёлым

Супер! Если завтра к вечеру допилишь будет супер — успеем показать на ревью

2023-12-01 00:07 UTC, kavabunga approved these changes
Вроде все зашибись! Можно будет потом косметически поправить, но функционал вроде весь на месте 🦾

2023-12-01 07:54 UTC, merged