feature/cards-list
Online-discount-card-service/odcs-frontend pull request #30
Opened 2023-11-06 10:19 UTC by HelgaMilne

Добавила компонент CardList и его состовляющие. 
Stories к ним в самом простом виде, еще не разобралась в этой теме.

2023-11-07 12:59 UTC, kavabunga requested changes
Посмотри, с типами в паре мест есть проблемы. Пометил!

2023-11-07 12:59 UTC, kavabunga commented on src/entities/card/index.tsx
> +  onClickCard(): void;
Тут кажется нужно указать типы аргументов. Лучше, наверное деструктурировать их, а если оставить как здесь, то можно условно так:
`a: string, b: string, c: string`
Сейчас ts подсвечивает там где вызываешь функцию.

2023-11-07 12:59 UTC, kavabunga commented on src/entities/card/index.tsx
> +  onClickLike(): void;
Тоже лучше указать тип аргумента

2023-11-07 12:59 UTC, kavabunga commented on src/entities/card/index.tsx
> +          sx={{
Кажется, лучше выносить стили, особенно когда их так много в отдельный файл. Посмотри, как в header сделано — там рядом с index.tsx лежит style.ts и в нем объект со стилями.

2023-11-07 12:59 UTC, kavabunga commented on src/widgets/cards-list/index.tsx
> +  onClickAddCard,
Тут ts ругается, нужно типизировать

2023-11-07 12:59 UTC, kavabunga commented on src/widgets/cards-list/index.tsx
> +      columns={{ xs: 12, sm: 12, md: 12 }}
Достаточно указать для xs количество колонок. А остальные нужны если оно будет меняться на более высоких разрешениях.
```suggestion
      columns={{ xs: 12 }}
```

2023-11-07 12:59 UTC, kavabunga commented on src/widgets/cards-list/index.tsx
> +const cards: {
Может вынести тоже в соседний файл? Или в shared/data/ например? Так в компоненте сразу появится пропс, который потом будем использовать чтобы реальные данные в него закидывать?

2023-11-07 12:59 UTC, kavabunga commented on src/entities/card/index.tsx
> +import { Paper } from '@mui/material';
В импортах можно объединять импорты из одной библиотеки

```suggestion
import { Box, Paper } from '@mui/material';
```

2023-11-07 15:45 UTC, kirei-io submitted a review, later dismissed

2023-11-07 15:45 UTC, kirei-io commented on src/widgets/cards-list/index.tsx
> +const cards: {
согласен можно вынести все мок данные в `/shared/mock`

2023-11-08 09:52 UTC, kavabunga approved these changes
Оставил в коде комменты, можно потом порефакторить

2023-11-08 09:52 UTC, kavabunga commented on src/widgets/cards-list/index.tsx
> +  }
```suggestion
//NOTE: Console outputs while no button logic developed
  function handleClickCard(name: string, number: string, url: string): void {
    console.log(`card ${name}, ${number}, ${url}, is clicked`);
  }

  function handleClickLike(card: CardProps): void {
    console.log(`card ${card} is liked`);
  }

  function handleAddCard(): void {
    console.log('card is added');
  }
```

2023-11-08 09:52 UTC, kavabunga commented on src/widgets/cards-list/index.tsx
> +          text="Добавить новую&nbsp;карту"
Очень круто &npsp! Надо в остальных компонентах в проекте потом порефакторить так! 🦾

2023-11-08 09:52 UTC, kavabunga commented on src/stories/card.stories.ts
> +} satisfies Meta<typeof Card>;
Здесь можно потом добавить `argTypes` чтобы можно было в сторибуке подставлять разные юрлы и смотреть как будет карта выглядеть. Для дизайнеров может быть полезно!

2023-11-08 09:52 UTC, kavabunga commented on src/features/add-card-button/ui/index.tsx
> +      }}
Можно потом вынести в style.ts

2023-11-08 09:52 UTC, kavabunga commented on src/entities/card/styles.ts
Чисто получилось! Свои компоненты так потом переделаю тоже!

2023-11-08 09:52 UTC, kavabunga commented on src/entities/card/index.tsx
> +      </IconButton>
Можно потом посмотреть компонент Card в MUI и если он лучше чем Paper подойдет — отрефакторить.

2023-11-08 09:52 UTC, kavabunga commented on src/entities/card/index.tsx
> +export const Card: FC<CardProps> = ({ card, onClickCard, onClickLike }) => {
Мне кажется если сделать пропс с опцией "тип карты", этот компонент будет более переиспользуемым. Для начала можно иметь два типа — с кнопкой лайка и возможностью клика по карте и без них. У нас есть несколько экранов, где карты без лайков и без возможности кликнуть по ним используются. Думаю можно уже начать использовать этот компонент везде, а потом отрефакторить.

2023-11-08 10:17 UTC, merged