feat: added added-card page
Online-discount-card-service/odcs-frontend pull request #32
Opened 2023-11-06 15:26 UTC by Taswikaa

Страница добавленной карты. Ещё не смотрел как мы будем добавлять штрихкод, поэтому пока просто затычка

2023-11-07 13:32 UTC, kavabunga requested changes
Добавил пару комментов! Там сейчас плющит футер — предложил как починить.

2023-11-07 13:32 UTC, kavabunga commented on src/pages/AddedCard.tsx
> +      ></Header>
```suggestion
      <Header
        user={{ name: 'иван' }}
        isLoggedIn={true}
        type="standard"
      />
```

2023-11-07 13:32 UTC, kavabunga commented on src/pages/AddedCard.tsx
> +        sx={{
Здесь и дальше можно стили вынести в отдельный style.ts, как сейчас в header сдедлано. К тому же тут есть повторяющиеся в кнопках внизу

2023-11-07 13:32 UTC, kavabunga commented on src/pages/AddedCard.tsx
> +      sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}
Сейчас футер сплющивает, ему нужна вся ширина. Я бы делал stretch и поправил бы горизонтальные паддинги у компонентов. И еще у бокса карты ширину, чтобы тянулась.

```suggestion
      sx={{ display: 'flex', flexDirection: 'column', alignItems: 'stretch' }}
```

2023-11-07 13:32 UTC, kavabunga commented on src/pages/AddedCard.tsx
> +            width: '20.5rem',
Так вместе со stretch на уровне выше будет тянуться

```suggestion
            width: '100%',
```

2023-11-07 13:32 UTC, kavabunga commented on src/pages/AddedCard.tsx
> +            <FavoriteBorderIcon></FavoriteBorderIcon>
```suggestion
            <FavoriteBorderIcon />
```

2023-11-07 13:32 UTC, kavabunga commented on src/pages/AddedCard.tsx
> +          <CreateIcon></CreateIcon>
```suggestion
          <CreateIcon />
```

2023-11-07 13:32 UTC, kavabunga commented on src/pages/AddedCard.tsx
> +      <Box sx={{ padding: '1.5rem 0 0', minWidth: '20.5rem' }}>
Догадываюсь, что это была очень нелегкая задача сверстать копию инпута на других компонентах! Но рискну предложить вместо этого сделать здесь инпут задизейбленый по умолчанию. А при нажатии на кнопку редактирования вверху страницы разблокировать эти инпуты и давать возможность менять данные 😬

2023-11-07 13:32 UTC, kavabunga commented on src/pages/AddedCard.tsx
> +      <Box sx={{ padding: '1.5rem 0 0', minWidth: '20.5rem' }}>
Тоже можно инпут disabled

2023-11-07 13:32 UTC, kavabunga commented on src/pages/AddedCard.tsx
> +      <AppFooter></AppFooter>
```suggestion
      <AppFooter />
```

2023-11-07 14:09 UTC, Taswikaa commented on src/pages/AddedCard.tsx
> +      <Box sx={{ padding: '1.5rem 0 0', minWidth: '20.5rem' }}>
Это инпут, мы разве можем менять номер карты?

2023-11-07 14:40 UTC, kavabunga commented on src/pages/AddedCard.tsx
> +      <Box sx={{ padding: '1.5rem 0 0', minWidth: '20.5rem' }}>
Ну да, а почему не можем? Мы же никак не валидируем номер при создании карты, а пользователь может ошибиться в цифрах

2023-11-07 16:18 UTC, Taswikaa commented
@kirei-io Внёс все изменения, добавил библиотеку react-barcode. Не стал только стили выносить, их здесь не так много

2023-11-08 21:08 UTC, kirei-io approved these changes

2023-11-08 21:20 UTC, kavabunga approved these changes
👀

2023-11-08 21:20 UTC, merged